#!/bin/sh

home="/usr/share/supplicant"
config_file="${home}/conf.lua"
authc_file="${home}/supplicant.conf"
prog="${home}/supplicant.lua"
script_running="${home}/supplicant.pid"
connect_status="${home}/supplicant.status"
info_log="${home}/info.log"
error_log="${home}/error.log"

start(){
	if [ -e ${script_running} ]; then
		return 0
	fi
	lua ${prog} 1> /dev/null 2> ${error_log} & pid=$!
	echo ${pid} > ${script_running}
	if [ "${pid}" != "" ]; then
		kill -0 ${pid} &> /dev/null
		if [ "$?" == "0" ]; then
			return 0
		fi
	fi
}

stop() {
	if [ ! -e ${script_running} ]; then
		return 0
	fi
	
	local spid=`cat ${script_running}`
	if [ "${spid}" != "" ]; then
		kill -9 ${spid} &> /dev/null
		rm ${script_running}
	fi
	return 0
}

status() {
    local cur_date=`date "+%Y-%m-%d %H:%M:%S"`
    local running=-1
    if [ -e ${script_running} ]; then
		local spid=`cat ${script_running}`
		if [ "${spid}" != "" ]; then
			kill -0 ${spid} &> /dev/null
			if [ "$?" == "0" ]; then
				running=0
			fi
		fi
	fi
	
	local status=`cat ${connect_status} 2> /dev/null`
	if [ "${status}" == "online" ]; then
		status="已连接"
	else
		status="已断开"
	fi
	
	local program=""
	if [ ${running} == -1 ]; then
		rm ${script_running} &> /dev/null
		program="stopped"
	else
		program="running"		
	fi
	if [ ! -e ${info_log} ]; then
		echo -n > ${info_log}
	fi
	local info="`cat ${info_log} 2> /dev/null`"
	local error="`cat ${error_log} 2> /dev/null`"

	echo '{"status": "'${program}'", "msg": "拨号状态： '${status}'<br/>时间: '${cur_date}'<br/>日志: <br/>'${error}'<br/>'${info}'"}'

}

reconfigure() {
	cp ./supplicant.conf ${home}/
	
	local dhcp='0'
	local version='3.8.2'
	echo "#!/usr/bin/lua" > $config_file
	echo "dhcp='$dhcp'" >> $config_file
	echo "version='$version'" >> $config_file
	local mac_addr=$(uci get network.wan.macaddr 2> /dev/null)
	echo "mac_addr='$mac_addr'" >> $config_file

	stop
	start
	return 0
}

## 安装的时候调用
install() {
	if [ ! -e ${home} ]; then
		mkdir ${home}
	fi
	cp -r ./ ${home}

	cp ${home}/supplicant /etc/init.d/
	chmod +x /etc/init.d/supplicant

	ln -sf /etc/init.d/supplicant /etc/rc.d/S95supplicant
	ln -sf /etc/init.d/supplicant /etc/rc.d/K95supplicant
	reconfigure
	start
	return 0
}

## 卸载的时候调用
uninstall() {
    stop
    ##删除定时任务、开机启动
	sed -i '/supplicant/d' /etc/crontabs/root
	rm -f /etc/rc.d/S95supplicant
	rm -f /etc/rc.d/K95supplicant
	rm -f /etc/init.d/supplicant
	if [ -d ${home} ]; then 
		rm -r ${home} &> /dev/null
	fi 
    return 0
}